# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/${PROJECT_ID}/terraform', './terraform']
- name: 'eu.gcr.io/${PROJECT_ID}/terraform'
  args: ['version']
images: ['eu.gcr.io/${PROJECT_ID}/terraform']
